### ISSUE TITLE
yabgpd execution error

### ISSUE THREAD

**Issue by skchao** [smartbgp/yabgp#107]
Hi, 
I seek your advice for the next step since I run into these errors:

(yabgp-virl)root@ubuntu-14-04-6-server-amd64:~/yabgp# yabgpd --bgp-local_addr=192.168.14.4 --bgp-local_as=1234 --bgp-remote_add=192.168.14.1 --bgp-remote_as=1234
Traceback (most recent call last):
  File "/usr/local/bin/yabgpd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: stevedore>=1.5.0

**Comment by meidli** [comment]
Hi, @skchao 

It looks like that your environment missing the dependency stevedore>=1.5.0, you can use the command ```pip list``` to check all dependencies. If ```stevedore``` do not involved in there, run the command ```pip install stevedore==1.30.0``` to install it, and then try to run yabgpd executor again.

**Comment by skchao** [comment]
> pip install stevedore==1.30.0

Thanks, meidli. It works!
