### ISSUE TITLE
any clue for the error I see when I test with POSTMAN API request?

### ISSUE THREAD

**Issue by skchao** [smartbgp/yabgp#108]
Hi any clue or advice about this error:

2019-12-20 13:58:50,413.413 1662 INFO yabgp.api.utils [-] API request url http://10.219.83.232:8801/v1/peer/192.168.14.1/send/update?Content-Type=application%2Fjson
2019-12-20 13:58:50,413.413 1662 INFO yabgp.api.utils [-] API query string Content-Type=application/json
2019-12-20 13:58:50,413.413 1662 INFO yabgp.api.utils [-] API request method POST
2019-12-20 13:58:50,413.413 1662 INFO yabgp.api.utils [-] API POST data None
2019-12-20 13:58:50,413.413 1662 ERROR flask.app [-] Exception on /v1/peer/192.168.14.1/send/update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_httpauth.py", line 61, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yabgp/api/utils.py", line 39, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yabgp/api/utils.py", line 48, in decorator
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yabgp/api/v1.py", line 120, in send_update_message
    attr = json_request.get('attr') or {}

Thanks!
/Kevin Chao

**Comment by xiaopeng163** [comment]
could you please share your postman data especially the POST json ?

**Comment by skchao** [comment]
> could you please share your postman data especially the POST json ?
here you go:
POST> 10.219.83.232:8801//v1/peer/192.168.14.1/send/update?Content-Type=application/json

**Comment by skchao** [comment]
hi, 
Sorry I made mistake myself, my json format POST body has something wrong. no question now.
