### ISSUE TITLE
netaddr issue for python3

### ISSUE THREAD

**Issue by xiaopeng163** [smartbgp/yabgp#44]
```
2017-08-08 15:46:45,160.160 9719 ERROR yabgp.core.protocol connectionMade 100 [-] argument of type 'DictDotLookup' is not iterable
2017-08-08 15:46:45,162.162 9719 DEBUG yabgp.core.protocol connectionMade 102 [-] Traceback (most recent call last):
  File "/Users/penxiao/tmp/yabgp/yabgp/core/protocol.py", line 95, in connectionMade
    if 'IPv6' in local_host_addr.info:
TypeError: argument of type 'DictDotLookup' is not iterable
```

```
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 08:49:46)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netaddr
>>> ip = netaddr.IPAddress('10.1.1.1')
>>> ip.info
{'IPv4': [{'date': '1995-06',
 'designation': 'IANA - Private Use',
 'prefix': '10/8',
 'status': 'Reserved',
 'whois': ''}]}
>>> 'IPv6' in ip.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'DictDotLookup' is not iterable
>>>
```

**Comment by xiaopeng163** [comment]
no problems in python 2
```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netaddr
>>> ip = netaddr.IPAddress('10.1.1.1')
>>> ip.info
{'IPv4': [{'date': '1995-06',
 'designation': 'IANA - Private Use',
 'prefix': '10/8',
 'status': 'Reserved',
 'whois': ''}]}
>>> type(ip.info)
<class 'netaddr.core.DictDotLookup'>
>>> "IPv6" in ip.info
False
>>>
```

**Comment by meidli** [comment]
Fixed! please check.

    Python 3.4.1 (default, Aug  7 2017, 20:27:12) 
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import netaddr
    >>> ip = netaddr.IPAddress('10.1.1.1')
    >>> 'IPv6' in ip.info
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: argument of type 'DictDotLookup' is not iterable
    >>> 'IPv6' in ip.info.__iter__()
    False

**Comment by xiaopeng163** [comment]
thanks @meidli
