### ISSUE TITLE
Unable to establish BGP Labeled Unicast neighborship

### ISSUE THREAD

**Issue by skanagal** [smartbgp/yabgp#84]
I get this error while trying to establish a BGP-LU relationship. It works with EXABGP but not with YABGP. Any know issue around this? The end point is an Arista switch.

```
2018-08-21 18:20:27,713.713 24959 INFO yabgp.core.fsm [-] [172.30.154.56]State is now:OPENSENT
2018-08-21 18:20:27,714.714 24959 ERROR yabgp.core.protocol [-] unpack requires a string argument of length 4
2018-08-21 18:20:27,715.715 24959 INFO yabgp.core.protocol [-] [172.30.154.56]A BGP KeepAlive message was received from peer.
```

**Comment by xiaopeng163** [comment]
@skanagal could you please add --verbose  when you run yabgpd, and give me the error log again?

and at the same time, if you cloud use tcpdump to capture the packets and send them to use, it will be very helpful.

like:

```sh
# tcpdump -i eth0 -w yabgp.pcap host xx.xx.xx.xx
```
eth0 is the interface used to establish BGP session

xx.xx.xx.xx is the remote peer address

**Comment by skanagal** [comment]
My apologies, I should have done that in the first place :) 

So the verbose output looks like below. Looks like the error is occuring when protocol.py is being run. I also attached the pcap as requested.

```
2018-08-21 18:44:22,239.239 25144 DEBUG yabgp.core.protocol parse_buffer 219 [-] Traceback (most recent call last):
  File "/home/arista/.local/lib/python2.7/site-packages/yabgp/core/protocol.py", line 186, in parse_buffer
    self._open_received(timestamp=t, msg=msg)
  File "/home/arista/.local/lib/python2.7/site-packages/yabgp/core/protocol.py", line 432, in _open_received
    parse_result = open_msg.parse(msg)
  File "/home/arista/.local/lib/python2.7/site-packages/yabgp/message/open.py", line 171, in parse
    afi, safi, send_rev = struct.unpack('!HBB', capability.capa_value)
error: unpack requires a string argument of length 4

2018-08-21 18:44:22,239.239 25144 INFO yabgp.core.protocol _keepalive_received 371 [-] [172.30.154.56]A BGP KeepAlive message was received from peer.
```



[yabgp.pcap.zip](https://github.com/smartbgp/yabgp/files/2308612/yabgp.pcap.zip)

**Comment by skanagal** [comment]
Yes, it works, thanks for your help

**Comment by xiaopeng163** [comment]
ok,  if you meet other problems in the future, please open issues, and we will check them asap.
